# _config.yml
title: Viatges
description: Comparteixo les meves aventures.
baseurl: "" # Deixa-ho buit si és la pàgina principal del repositori
url: "https://guillemlpc.github.io" # URL del teu Github Pages
theme: minima # Canvia-ho pel tema que vulguis utilitzar
permalink: /:categories/:year/:month/:day/:title/

# Configuració de Markdown
timezone: Europe/Madrid
markdown: kramdown
kramdown:
  input: GFM

# Configuració de plugins (opcional)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Altres opcions (opcionals)
highlighter: rouge
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Dades personalitzades (opcional)
author:
  name: Guillem
  email: guillemlc9@gmail.com
